import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    az: {
        welcome: "Xoş Gəldiniz",
        welcome_tag: "Xoş Gəldiniz!",
        login: "Daxil Ol",
        register: "Qeydiyyat",
        cart: "Səbət",
        menu: "Menyu",
        total: "Cəmi",
        add: "Əlavə et",
        empty_cart: "Səbət boşdur",
        checkout: "Ödəniş et",
        search: "Axtarış...",
        search_food: "Yemək axtar...",
        language: "Dil",
        settings: "Tənzimləmələr",
        theme: "Mövzu",
        theme_light: "Açıq",
        theme_dark: "Tünd",
        help: "Kömək",
        forgot_password: "Şifrəmi unutdum?",
        send: "Göndər",
        back: "Geri Qayıt",
        email: "E-mail",
        password: "Şifrə",
        name: "Ad Soyad",
        all: "Hamısı",
        all_foods: "Bütün Yeməklər",
        foods: "Yeməklər",
        results: "Nəticələr",
        menu_empty: "Menyu hələ boşdur",
        select_table: "Masa seç",
        table: "Masa",
        call: "Zəng et",
        address: "Ünvan",
        demo_mode: "Göstəriş Rejimi (Demo)",
        demo_desc: "Siz hazırda test məlumatlarını görürsünüz. Öz menyunuzu yaratmaq üçün admin panelə keçin.",
        go_admin: "Adminə Keç",
        special_info: "Xüsusi Məlumat",
        service_fee: "Sifarişinizə 10% servis haqqı əlavə edilir",
        info: "Məlumat",
        table_number: "Masa Nömrəniz",
        table_desc: "Sifarişin doğru yerə çatması üçün",
        eg: "məs:",
        confirm: "Təsdiqlə",
        invalid_number: "Düzgün nömrə daxil edin",
        added_to_cart: "Səbətə əlavə edildi",
        table_selected: "seçildi",
        view_cart: "Səbəti Gör",
        my_order: "Sifarişim",
        not_selected: "seçilməyib",
        cart_empty: "Səbətiniz boşdur",
        per_piece: "/ ədəd",
        subtotal: "Ara cəm",
        service_fee_title: "Servis haqqı",
        send_whatsapp: "WhatsApp ilə Göndər",
        select_table_first: "Əvvəlcə masa nömrəsi seçin!",
        order_table: "Sifariş – Masa",
        total_label: "Ümumi",
        features: "Üstünlüklər",
        pricing: "Tariflər",
        demo_menu: "Nümunə Menyu",
        nav_login: "Daxil Ol",
        brand_name: "QR Menyu",
        how_it_works: "Necə İşləyir?",
        free: "Pulsuz",
        per_month: "/ay",
        per_year: "/il",

        create_digital_menu: "Restoranınız üçün rəqəmsal menyu yaradın",
        reset_password: "Şifrəni Yenilə",
        fill_all_fields: "Bütün sahələri doldurun",
        account_not_found: "Bu e-mail ilə hesab tapılmadı",
        wrong_password: "Şifrə yanlışdır",
        welcome_back: "👋 Xoş gəldiniz!",
        password_min_length: "Şifrə ən az 6 simvol olmalıdır",
        email_exists: "Bu e-mail artıq qeydiyyatdadır",
        account_created: "🎉 Hesab yaradıldı,",
        enter_email: "E-mail ünvanınızı daxil edin",
        logged_out: "👋 Çıxış edildi",
        restaurant: "Restoran",
        categories: "Kateqoriyalar",
        settings: "Tənzimləmələr",
        password_reset_sent: "Şifrə sıfırlama linki göndərildi:",
        register_button: "Qeydiyyatdan Keç",
        back_to_home: "Ana Səhifəyə Qayıt",
        view_menu: "Menyuya Bax",
        logout: "Çıxış",
        search_dot: "Axtar...",
        search_btn: "Axtar",
        live_preview: "Canlı Önbaxış",

        visual_info: "Vizual Məlumatlar",
        restaurant_name: "Restoran Adı *",
        slogan: "Slogan",
        cover_image: "Örtük Şəkli (Cover)",
        logo_image: "Loqo / Profil Şəkli",
        contact: "Əlaqə",
        phone: "Telefon",
        whatsapp_number: "WhatsApp",
        other: "Digər",
        work_hours: "İş Saatları",
        wifi_password: "WiFi Şifrəsi",
        rating: "Reytinq (1–5)",
        save: "Yadda Saxla",
        delete_image: "Şəkli sil",
        select_image: "Şəkil seçin (Klikləyin)",
        image_uploaded: "✅ Şəkil yükləndi",
        image_failed: "❌ Şəkil yüklənə bilmədi",
        name_required: "⚠️ Restoran adı mütləqdir",
        saved: "✅ Yadda saxlanıldı!",

        // Landing Page
        hero_badge: "🚀 Restoranınız üçün Rəqəmsal Gələcək",
        hero_title_1: "Rəqəmsal Menyu ilə",
        hero_title_2: "Müştəri Təcrübəsini",
        hero_title_highlight: "Yeniləyin",
        hero_subtitle: "Müştəriləriniz mobil telefonlarından saniyələr içində menyunuza daxil olsun. Kağız menyu xərclərinə son qoyun və restoranınızı bir addım öndə aparın.",
        start_now: "İndi Başlayın",
        view_demo: "Demo Menyuya Bax",
        mockup_qr: "QR Menyu'ya",
        fast_order: "Sürətli Sifariş",
        safe_payment: "Təhlükəsiz Ödəniş",
        stat_1_label: "Aktiv Restoran",
        stat_2_label: "Aylıq İstifadəçi",
        stat_3_label: "Müştəri Razılığı",
        create_account: "Hesab Yarat",
        success: "Uğurlu!",
        dashboard: "İdarəetmə Paneli",
        customer_view: "Müştəri Baxışı",
        step_1_title: "Qeydiyyatdan Keçin",
        step_1_desc: "Saniyələr içində hesabınızı yaradın və restoran məlumatlarını daxil edin.",
        step_2_title: "Menyunuzu Yaradın",
        step_2_desc: "Yeməkləri, şəkilləri və qiymətləri asanlıqla panelimizdən əlavə edin.",
        step_3_title: "QR Kodunuzu Paylaşın",
        step_3_desc: "QR kodunuzu masalara yerləşdirin, müştərilər menyunu anında görsün.",
        scan: "Skan",
        why_us: "Niyə Bizim Platforma?",
        why_us_desc: "Ən müasir funksionallıqları bir yerdə topladıq",
        feature_1_title: "Fərqli QR Dizaynları",
        feature_1_desc: "8 fərqli dizayn və limitsiz rəng seçimləri ilə öz QR kodunuzu yaradın.",
        feature_2_title: "Çoxdilli Dəstək",
        feature_2_desc: "Müştəriləriniz üçün menyunu fərqli dillərdə təqdim etmək imkanı.",
        feature_3_title: "Real Vaxt Yenilənmə",
        feature_3_desc: "Qiymət və ya məhsul dəyişikliyi saniyələr içində tətbiq olunur.",
        feature_4_title: "Mobil Proqram Lazım Deyil",
        feature_4_desc: "Müştərilər heç bir tətbiq yükləmədən birbaşa brauzerdən istifadə edir.",
        testi_title: "Restoran Sahibləri Nə Deyir?",
        testi_desc: "Bizə güvənən yüzlərlə restorana qatılın",
        testi_1: "\"Əvvəllər menyuları çap etdirmək çox xərc tələb edirdi. İndi bir kliklə qiymətləri yeniləyirik və müştərilər dizayna bayılır.\"",
        testi_type_1: "Premium Restoran",
        testi_2: "\"Müştərilərimiz dizaynı çox bəyənir. Sifariş prosesi qat-qat sürətlənib və ofisiantların işi xeyli yüngülləşib.\"",
        testi_type_2: "Lounge & Bar",
        testi_3: "\"İstifadəsi o qədər rahatdır ki, heç bir texniki biliyə ehtiyac yoxdur. Platformaya keçəndən bəri xərclərimiz 30% azalıb.\"",
        testi_type_3: "Ailəvi Restoran",
        pricing_title: "Sadə və Şəffaf Qiymətlər",
        free: "Pulsuz",
        per_month: "/ay",
        per_year: "/il",
        most_popular: "Ən Çox Seçilən",
        best_value: "Ən Sərfəli",
        monthly_sub: "Aylıq Abunə",
        yearly_sub: "İllik Abunə",
        go_premium: "Premium-a Keç",
        go_yearly: "İllik-ə Keç",
        start_free: "Pulsuz Başla",
        cta_title: "Bizimlə Başlamağa Hazırsınız?",
        cta_desc: "Bir neçə dəqiqə içində restoranınızı rəqəmsallaşdırın.",
        contact_wa: "WhatsApp ilə əlaqə",
        footer_desc: "Restoranlar üçün ən yaxşı rəqəmsal həll yolu.",
        platform: "Platforma",
        support: "Dəstək",
        privacy: "Məxfilik siyasəti",
        terms: "İstifadə şərtləri",
        contact_us: "Bizimlə əlaqə",
        copyright: "© 2026 QR Menyu AZ. Bütün hüquqlar qorunur.",
        
        pr_f_1: "50 məhsul limiti",
        pr_f_2: "Standart QR dizayn",
        pr_f_3: "Limitsiz baxış",
        pr_f_4: "Prioritet dəstək",
        pr_f_5: "Limitsiz məhsul",
        pr_f_6: "Premium QR dizaynları",
        pr_f_7: "Şəkil optimizasiyası",
        pr_f_8: "24/7 Prioritet dəstək",
        pr_f_9: "2 ay hədiyyə",
        pr_f_10: "Xüsusi domen (məs: restoran.az)",
        pr_f_11: "VIP 24/7 Dəstək"
    },
    en: {
        welcome: "Welcome",
        welcome_tag: "Welcome!",
        login: "Login",
        register: "Register",
        cart: "Cart",
        menu: "Menu",
        total: "Total",
        add: "Add",
        empty_cart: "Cart is empty",
        checkout: "Checkout",
        search: "Search...",
        search_food: "Search food...",
        language: "Language",
        settings: "Settings",
        theme: "Theme",
        theme_light: "Light",
        theme_dark: "Dark",
        help: "Help",
        forgot_password: "Forgot password?",
        send: "Send",
        back: "Go Back",
        email: "E-mail",
        password: "Password",
        name: "Full Name",
        all: "All",
        all_foods: "All Foods",
        foods: "Foods",
        results: "Results",
        menu_empty: "Menu is empty",
        select_table: "Select Table",
        table: "Table",
        call: "Call",
        address: "Address",
        demo_mode: "Demo Mode",
        demo_desc: "You are currently viewing test data. Go to the admin panel to create your own menu.",
        go_admin: "Go to Admin",
        special_info: "Special Info",
        service_fee: "A 10% service fee is added to your order",
        info: "Info",
        table_number: "Table Number",
        table_desc: "To deliver the order to the right place",
        eg: "e.g.",
        confirm: "Confirm",
        invalid_number: "Please enter a valid number",
        added_to_cart: "Added to cart",
        table_selected: "selected",
        view_cart: "View Cart",
        my_order: "My Order",
        not_selected: "not selected",
        cart_empty: "Your cart is empty",
        per_piece: "/ piece",
        subtotal: "Subtotal",
        service_fee_title: "Service fee",
        send_whatsapp: "Send via WhatsApp",
        select_table_first: "Please select table number first!",
        order_table: "Order - Table",
        total_label: "Total",
        features: "Features",
        pricing: "Pricing",
        demo_menu: "Demo Menu",
        nav_login: "Login",
        brand_name: "QR Menu",
        how_it_works: "How it works?",
        free: "Free",
        per_month: "/mo",
        per_year: "/yr",

        create_digital_menu: "Create a digital menu for your restaurant",
        reset_password: "Reset Password",
        fill_all_fields: "Fill all fields",
        account_not_found: "Account with this email not found",
        wrong_password: "Wrong password",
        welcome_back: "👋 Welcome back!",
        password_min_length: "Password must be at least 6 characters",
        email_exists: "This email is already registered",
        account_created: "🎉 Account created,",
        enter_email: "Enter your e-mail address",
        logged_out: "👋 Logged out",
        restaurant: "Restaurant",
        categories: "Categories",
        settings: "Settings",
        password_reset_sent: "Password reset link sent to:",
        register_button: "Sign Up",
        back_to_home: "Back to Home",
        view_menu: "View Menu",
        logout: "Logout",
        search_dot: "Search...",
        search_btn: "Search",
        live_preview: "Live Preview",

        visual_info: "Visual Information",
        restaurant_name: "Restaurant Name *",
        slogan: "Slogan",
        cover_image: "Cover Image",
        logo_image: "Logo / Profile Image",
        contact: "Contact",
        phone: "Phone",
        whatsapp_number: "WhatsApp",
        other: "Other",
        work_hours: "Working Hours",
        wifi_password: "WiFi Password",
        rating: "Rating (1-5)",
        save: "Save",
        delete_image: "Delete Image",
        select_image: "Select Image (Click)",
        image_uploaded: "✅ Image uploaded",
        image_failed: "❌ Failed to upload image",
        name_required: "⚠️ Restaurant name is required",
        saved: "✅ Saved successfully!",

        hero_badge: "🚀 Digital Future for Your Restaurant",
        hero_title_1: "Upgrade Customer Experience",
        hero_title_2: "with a",
        hero_title_highlight: "Digital Menu",
        hero_subtitle: "Let your customers access your menu from their mobile phones in seconds. Eliminate paper menu costs and stay one step ahead.",
        start_now: "Start Now",
        view_demo: "View Demo Menu",
        mockup_qr: "Welcome to",
        fast_order: "Fast Ordering",
        safe_payment: "Safe Payment",
        stat_1_label: "Active Restaurants",
        stat_2_label: "Monthly Users",
        stat_3_label: "Customer Satisfaction",
        create_account: "Create Account",
        success: "Success!",
        dashboard: "Dashboard",
        customer_view: "Customer View",
        step_1_title: "Register",
        step_1_desc: "Create your account in seconds and enter restaurant details.",
        step_2_title: "Create Menu",
        step_2_desc: "Easily add meals, images and prices from our panel.",
        step_3_title: "Share QR Code",
        step_3_desc: "Place your QR code on tables, customers see menu instantly.",
        scan: "Scan",
        why_us: "Why Our Platform?",
        why_us_desc: "We gathered modern features in one place",
        feature_1_title: "Various QR Designs",
        feature_1_desc: "Create your QR code with 8 designs and unlimited colors.",
        feature_2_title: "Multilingual Support",
        feature_2_desc: "Ability to present menu in different languages.",
        feature_3_title: "Real Time Update",
        feature_3_desc: "Price or product changes apply in seconds.",
        feature_4_title: "No App Required",
        feature_4_desc: "Customers use directly from browser without downloading anything.",
        testi_title: "What Owners Say?",
        testi_desc: "Join hundreds of restaurants trusting us",
        testi_1: "\"Printing menus used to cost a lot. Now we update prices with a click and customers love the design.\"",
        testi_type_1: "Premium Restaurant",
        testi_2: "\"Customers really like the design. Ordering process is much faster and waiters' work is easier.\"",
        testi_type_2: "Lounge & Bar",
        testi_3: "\"It's so easy to use, no technical knowledge needed. Since switching, our costs dropped by 30%.\"",
        testi_type_3: "Family Restaurant",
        pricing_title: "Simple & Transparent Pricing",
        free: "Free",
        per_month: "/mo",
        per_year: "/yr",
        most_popular: "Most Popular",
        best_value: "Best Value",
        monthly_sub: "Monthly Subscription",
        yearly_sub: "Yearly Subscription",
        go_premium: "Get Premium",
        go_yearly: "Get Yearly",
        start_free: "Start Free",
        cta_title: "Ready to Start With Us?",
        cta_desc: "Digitize your restaurant in just a few minutes.",
        contact_wa: "Contact via WhatsApp",
        footer_desc: "The best digital solution for restaurants.",
        platform: "Platform",
        support: "Support",
        privacy: "Privacy Policy",
        terms: "Terms of Use",
        contact_us: "Contact Us",
        copyright: "© 2026 QR Menu AZ. All rights reserved.",
        
        pr_f_1: "50 products limit",
        pr_f_2: "Standard QR design",
        pr_f_3: "Unlimited views",
        pr_f_4: "Priority support",
        pr_f_5: "Unlimited products",
        pr_f_6: "Premium QR designs",
        pr_f_7: "Image optimization",
        pr_f_8: "24/7 Priority support",
        pr_f_9: "2 months free",
        pr_f_10: "Custom domain (e.g. restaurant.com)",
        pr_f_11: "VIP 24/7 Support"
    },
    ru: {
        welcome: "Добро пожаловать",
        welcome_tag: "Добро пожаловать!",
        login: "Войти",
        register: "Регистрация",
        cart: "Корзина",
        menu: "Меню",
        total: "Итого",
        add: "Добавить",
        empty_cart: "Корзина пуста",
        checkout: "Оформить заказ",
        search: "Поиск...",
        search_food: "Поиск еды...",
        language: "Язык",
        settings: "Настройки",
        theme: "Тема",
        theme_light: "Светлая",
        theme_dark: "Темная",
        help: "Помощь",
        forgot_password: "Забыли пароль?",
        send: "Отправить",
        back: "Назад",
        email: "E-mail",
        password: "Пароль",
        name: "Имя Фамилия",
        all: "Все",
        all_foods: "Вся Еда",
        foods: "Блюда",
        results: "Результаты",
        menu_empty: "Меню пустое",
        select_table: "Выбрать стол",
        table: "Стол",
        call: "Позвонить",
        address: "Адрес",
        demo_mode: "Демо Режим",
        demo_desc: "В настоящее время вы просматриваете тестовые данные. Перейдите в панель администратора, чтобы создать свое меню.",
        go_admin: "В админ панель",
        special_info: "Особая информация",
        service_fee: "К вашему заказу добавляется 10% сервисный сбор",
        info: "Инфо",
        table_number: "Номер вашего стола",
        table_desc: "Чтобы доставить заказ в нужное место",
        eg: "напр.",
        confirm: "Подтвердить",
        invalid_number: "Введите правильный номер",
        added_to_cart: "Добавлено в корзину",
        table_selected: "выбран",
        view_cart: "Посмотреть корзину",
        my_order: "Мой заказ",
        not_selected: "не выбран",
        cart_empty: "Ваша корзина пуста",
        per_piece: "/ шт.",
        subtotal: "Подытог",
        service_fee_title: "Сервисный сбор",
        send_whatsapp: "Отправить через WhatsApp",
        select_table_first: "Сначала выберите номер стола!",
        order_table: "Заказ - Стол",
        total_label: "Итого",
        features: "Особенности",
        pricing: "Тарифы",
        demo_menu: "Демо Меню",
        nav_login: "Войти",
        brand_name: "QR Меню",
        how_it_works: "Как это работает?",
        free: "Бесплатно",
        per_month: "/мес",
        per_year: "/год",

        create_digital_menu: "Создайте цифровое меню для вашего ресторана",
        reset_password: "Сброс пароля",
        fill_all_fields: "Заполните все поля",
        account_not_found: "Аккаунт с таким e-mail не найден",
        wrong_password: "Неверный пароль",
        welcome_back: "👋 Добро пожаловать!",
        password_min_length: "Пароль должен состоять минимум из 6 символов",
        email_exists: "Этот e-mail уже зарегистрирован",
        account_created: "🎉 Аккаунт создан,",
        enter_email: "Введите ваш e-mail",
        logged_out: "👋 Вы вышли из системы",
        restaurant: "Ресторан",
        categories: "Категории",
        settings: "Настройки",
        password_reset_sent: "Ссылка для сброса пароля отправлена на:",
        register_button: "Зарегистрироваться",
        back_to_home: "Вернуться на главную",
        view_menu: "Посмотреть меню",
        logout: "Выйти",
        search_dot: "Поиск...",
        search_btn: "Поиск",
        live_preview: "Предпросмотр",

        visual_info: "Визуальная информация",
        restaurant_name: "Название Ресторана *",
        slogan: "Слоган",
        cover_image: "Обложка (Cover)",
        logo_image: "Логотип / Профиль",
        contact: "Контакты",
        phone: "Телефон",
        whatsapp_number: "WhatsApp",
        other: "Другое",
        work_hours: "Часы работы",
        wifi_password: "Пароль WiFi",
        rating: "Рейтинг (1-5)",
        save: "Сохранить",
        delete_image: "Удалить фото",
        select_image: "Выберите фото (Кликните)",
        image_uploaded: "✅ Фото загружено",
        image_failed: "❌ Ошибка загрузки фото",
        name_required: "⚠️ Название обязательно",
        saved: "✅ Успешно сохранено!",

        hero_badge: "🚀 Цифровое будущее для вашего ресторана",
        hero_title_1: "Улучшите опыт клиентов",
        hero_title_2: "с помощью",
        hero_title_highlight: "Цифрового Меню",
        hero_subtitle: "Позвольте клиентам получать доступ к вашему меню со своих телефонов за секунды. Избавьтесь от затрат на бумажные меню.",
        start_now: "Начать сейчас",
        view_demo: "Посмотреть Демо Меню",
        mockup_qr: "Добро пожаловать в",
        fast_order: "Быстрый Заказ",
        safe_payment: "Безопасная Оплата",
        stat_1_label: "Активных Ресторанов",
        stat_2_label: "Пользователей в Месяц",
        stat_3_label: "Довольных Клиентов",
        create_account: "Создать Аккаунт",
        success: "Успешно!",
        dashboard: "Панель Управления",
        customer_view: "Вид Клиента",
        step_1_title: "Зарегистрируйтесь",
        step_1_desc: "Создайте аккаунт за секунды и введите данные ресторана.",
        step_2_title: "Создайте Меню",
        step_2_desc: "Легко добавляйте блюда, фото и цены из нашей панели.",
        step_3_title: "Поделитесь QR-кодом",
        step_3_desc: "Разместите QR-код на столах, клиенты сразу увидят меню.",
        scan: "Скан",
        why_us: "Почему Наша Платформа?",
        why_us_desc: "Мы собрали современные функции в одном месте",
        feature_1_title: "Разные Дизайны QR",
        feature_1_desc: "Создайте свой QR-код с 8 дизайнами и любыми цветами.",
        feature_2_title: "Многоязычность",
        feature_2_desc: "Возможность представить меню на разных языках.",
        feature_3_title: "Обновления в Реальном Времени",
        feature_3_desc: "Изменения цен или продуктов применяются мгновенно.",
        feature_4_title: "Без Приложений",
        feature_4_desc: "Клиенты используют прямо из браузера без загрузки.",
        testi_title: "Что Говорят Владельцы?",
        testi_desc: "Присоединяйтесь к сотням ресторанов",
        testi_1: "\"Печать меню раньше стоила дорого. Теперь мы обновляем цены одним кликом, и клиентам нравится дизайн.\"",
        testi_type_1: "Премиум Ресторан",
        testi_2: "\"Клиентам очень нравится дизайн. Процесс заказа стал намного быстрее, а работа официантов легче.\"",
        testi_type_2: "Лаунж и Бар",
        testi_3: "\"Очень просто в использовании. С момента перехода наши расходы сократились на 30%.\"",
        testi_type_3: "Семейный Ресторан",
        pricing_title: "Простые и Прозрачные Цены",
        free: "Бесплатно",
        per_month: "/мес",
        per_year: "/год",
        most_popular: "Самый Популярный",
        best_value: "Лучшая Цена",
        monthly_sub: "Ежемесячная Подписка",
        yearly_sub: "Годовая Подписка",
        go_premium: "Получить Премиум",
        go_yearly: "Получить на Год",
        start_free: "Начать Бесплатно",
        cta_title: "Готовы Начать с Нами?",
        cta_desc: "Оцифруйте свой ресторан всего за несколько минут.",
        contact_wa: "Связаться через WhatsApp",
        footer_desc: "Лучшее цифровое решение для ресторанов.",
        platform: "Платформа",
        support: "Поддержка",
        privacy: "Политика конфиденциальности",
        terms: "Условия использования",
        contact_us: "Связаться с нами",
        copyright: "© 2026 QR Menu AZ. Все права защищены.",
        
        pr_f_1: "Лимит 50 продуктов",
        pr_f_2: "Стандартный дизайн QR",
        pr_f_3: "Неограниченные просмотры",
        pr_f_4: "Приоритетная поддержка",
        pr_f_5: "Безлимитные продукты",
        pr_f_6: "Премиум дизайны QR",
        pr_f_7: "Оптимизация изображений",
        pr_f_8: "Приоритетная поддержка 24/7",
        pr_f_9: "2 месяца бесплатно",
        pr_f_10: "Кастомный домен (напр: restaurant.az)",
        pr_f_11: "VIP Поддержка 24/7"
    }
};

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState(() => {
        const params = new URLSearchParams(window.location.search);
        const urlLang = params.get('lang');
        if (urlLang && translations[urlLang]) {
            return urlLang;
        }

        const saved = localStorage.getItem('qrmenu_lang');
        if (saved && translations[saved]) {
            return saved;
        }

        const browserLang = navigator.language.split('-')[0];
        if (translations[browserLang]) {
            return browserLang;
        }

        return 'az';
    });

    useEffect(() => {
        localStorage.setItem('qrmenu_lang', lang);
        document.documentElement.lang = lang;
    }, [lang]);

    const t = (key) => {
        return translations[lang]?.[key] || translations['az'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => useContext(LanguageContext);
